name: PCP

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.7.*
  - pip=19.2.*
  - numpy=1.17.*
  - matplotlib=3.1.*
  - ipython=7.8.*
  - jupyter=1.0.*
  - jupyter_contrib_nbextensions=0.5.*
  - pip:
    - nbstripout==0.3.*
    - pysoundfile==0.9.*
